softeerbootcamp-2nd/be-chess

.idea/misc.xml
src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

[ajsthfldu] step-1 폰 생성

---

src/main/java/softeer2nd/Chess/Pawn.java
src/test/java/softeer2nd/Chess/PawnTest.java

1. Pawn 테스트 코드 작성
2. Pawn 클래스 구현
3. Pawn 테스트 코드 refactoring (문자열 중복 제거 및 verify 함수 분리)

[rbgus2002] step-1 폰 생성

---

src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

- Pawn 클래스 생성
- PawnTest 생성
- PawnTest에 Pawn create 시 색을 확인하는 테스트 생성
- create test가 pass되도록 Pawn class 수정
- 미션의 내용에 따라 PawnTest 리팩토링
- Junit Test에 대해서 잘 몰라서 알아보았습니다.
- 리팩토링 과정에서 어떻게 할 지에 대해 고민해보았습니다.

[jjy0709] step-1 폰 생성

---

.idea/misc.xml
src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

Pawn이라는 Class를 생성 후 테스트로 검증.
Pawn은 내부 변수 color에 자신의 색("white" / "black")을 저장하고 있고, getColor() 메서드를 통해 자신의 색을 반환
중복 코드를 제거하기 위해 verifyPawn이라는 메서드를 생성하여 사용하였는데, 무엇을 반환해야 중복이 최대한 줄어드는지 고민.
결론은 확인하는 로직을 전부 넣어 반환값 없이(void) 생성

[jst0951] step-1 폰 생성

---

.idea/jpa-buddy.xml
.idea/misc.xml
README.md
src/main/java/softeer2nd/Board.java
src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

- 체스게임 프로젝트 생성
- 기본 말인 Pawn을 흰색과 검정색으로 구분해서 생성 가능하도록 구현
- verifyPawn 메소드 구현할 때  메소드 안에서 Pawn을 구현해야 하는 부분을 고민함

[jeongyeonKimm] step-1 폰 생성

---

src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

- Pawn class 생성
- Pawn 생성 메소드 테스트

[dohyeon-han] step-1 폰 생성

---

.idea/misc.xml
src/main/java/softeer2nd/chess/sixPieces/Pawn.java
src/test/java/softeer2nd/chess/sixPieces/PawnTest.java

- Pawn 테스트 생성
- Pawn 클래스 생성
- Pawn 테스트 리팩토링
- 없습니다.

[Hypersand] step-1 폰 생성

---

README.md
src/main/java/softeer2nd/Unit/Pawn.java
src/test/java/softeer2nd/PawnTest.java

[ShinHeeEul] step-1 폰 생성

---

.idea/misc.xml
.idea/modules.xml
.idea/modules/be-chess.test.iml
src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/HelloTest.java
src/test/java/softeer2nd/PawnTest.java

1. Pawn class의 테스트코드 작성
2. 1을 바탕으로 한 Pawn class 구현
3. 코드 중복 제거를 위한 리팩토링
1. 테스트 코드 내에서 중복되는 요소를 찾아 이를 추출할 방법에 대해서 고민했다.
2. 많은 예외케이스를 고려하기 위한 테스트 코드 작성에 대해서 고민했다.
3. Pawn 클래스의 color 필드를 enum으로 따로 생성해 적용할 방법에 대해서 생각했다. 추가적인 공부가 필요할 것 같다.

[bumstead-bumstead] step-1 폰 생성

---

src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

Pawn생성을 위한 테스트 코드와 클래스 코드를 작성.
pawn 인스턴스는  흰색 / 검은색중 하나의 색을 갖으며, 게임 중 바뀔 수 없음.
Pawn의 색을 가리키는 변수 타입 -> String Type vs Enum Type

[springscomin] step-1 폰 생성

---

src/main/java/softeer2nd/Pawn.java
src/main/java/softeer2nd/exception/InvalidColorException.java
src/test/java/softeer2nd/PawnTest.java

- PawnTest 생성후 실패하는 코드 작성
- Pawn 클래스 생성. 변수 및 메서드 작성해서 테스트 성공하게끔 변경
- 중복 제거를 통한 리팩토링
- Pawn 클래스 생성시 black 또는 white 만 들어올 수 있게 해야함
- isEqualTo 메서드가 동일성과 동등성중에 무엇을 비교해주는지 확인 필요

[jjddhh] step-1 폰 생성

---

.idea/be-chess.iml
.idea/misc.xml
.idea/modules.xml
.idea/modules/be-chess.main.iml
.idea/modules/be-chess.test.iml
src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

체스 게임 중에서 가장 기본 말인 Pawn 클래스를 구현하고 어느 팀 말인지 구분하기 위해 white, black을 구분해 생성할 수 있도록 한다.
자바에 익숙지 않아서 Junit과 assertThat이 어떤 기능을 하는지 찾아 보면서 공부해야 했다.
verifyPawn 메소드를 어떤 식으로 구현해야 되는지에 대해서 많이 고민했다.

[sue06004] step-1 폰 생성

---

src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

- color 속성을 갖는 Pawn 클래스 구현
- 생성된 인스턴스의 color가 일치하는지 확인하는 테스트 코드 작성
- assertj 메소드 사용 방법
- 효율적인 Refactoring 방법 고민(중복 최소화)
- 테스트 라이브러리 익숙해지기
- 커밋 메시지 형식 통일 필요

[socra167] step-1 폰 생성

---

src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

- 폰 생성 클래스 (Pawn.java)
- 폰 생성 테스트 클래스 (PawnTest.java)
- 테스트 코드 작성
- 테스트 코드를 처음 작성해봐서 실행 방법을 공부했다.
- JUnit에 대해 더 알아보고 싶다.

[kimahhh] step-1 폰 생성

---

README.md
src/main/java/softeer2nd/chess/domain/piece/Pawn.java
src/test/java/softeer2nd/PawnTest.java

- 폰 생성 테스트 클래스를 먼저 구현 한 뒤, 테스트 클래스에 맞게 폰 클래스 구현
- 구현 과정에서 중복된 코드나 로직들은 최대한 하나로 묶어 리팩토링
- 색을 검증하는 테스트 로직 추가 구현
- JUnit과 assert를 사용한 테스트 코드가 익숙하지 않았다.
- assertThat을 사용하는 방법이 익숙하지 않았다.
- 오류가 나는 테스트 코드가 정상적으로 오류를 호출하는 방식의 테스트 코드를 작성해 보고 싶었다.
- 폰의 색, 플레이어의 선후공이 같은 의미를 가지므로 ENUM을 사용해야 하나 고민했지만 잘 사용해보지 않아 옳바른 선택인지 고민했다. 더 학습이 필요할 것 같다.
- 테스트 코드 작성이 익숙하지 않아 검정색, 흰색 외의 색을 받을 경우 폰의 색을 검증하는 테스트 코드를 작성해 보았다.
- 위 코드를 작성해 보면서 assertThat(타겟).메소드.메소드 의 기본 구성으로 이루어 진다는 것을 알았다.
- isEqualTo가 아닌 어레이 리스트를 활용한 isIn 메소드를 통해 검정색, 흰색이 들어오는지 테스트 코드를 작성해 보았다.

[ddingmin] step-1 폰 생성

---

README.md
src/test/java/chess/pieces/PawnTest.java

체스판인 Board 클래스를 생성 후 Pawn을 넣어 테스트
Pull Request가 Open되어 있는 상태에서 fork된 레포지토리에 커밋을 하면 해당 커밋 역시 반영된다는 사실을 알게 되었다.

[jongwon] step-2 체스판 생성

---

src/main/java/softeer2nd/Pawn.java
src/test/java/softeer2nd/PawnTest.java

- 폰 색상(color)을 속성으로 갖는 Pawn 클래스 구현
- JUnit을 이용하여 폰의 색상을 검증하는 테스트 코드 작성 
- commit을 만드는 기준에 대해 고민을 많이 했습니다.
- verifyPawn() 메서드에서 assert() 메서드를 사용해야 될 지 고민했습니다. 단일 책임 원칙을 생각하며 verifyPawn() 메서드는 색상의 일치 여부만 확인하고, 흐름제어는 create() 메서드에서 진행하는 것이 더 좋다고 생각했습니다.
- 폰 뿐만 아니라 다른 기물도 공통적으로 색상 속성을 가지기 때문에, 기물을 나타내는 부모 클래스의 필요성을 생각했습니다.

[csct3434] step-1 폰 생성

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java

boardTest 구현했습니다.
지금 boardTest 에서 가지고 있는 test가 하나여서 @beforeEach 를 구현해야하는지 아닌지를 고민했습니다.
Pawn 객체를 저장하는 컬렉션을 사용함으로 저장하기 전에 타입에 대한 체크를 해줍니다. 그래서 굳이 new Integer()같은 객체들에 대한 예외처리를 해주어야 하는지 고민했습니다.

[dydwo0740] step-2 체스판 생성

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/main/java/softeer2nd/chess/sixPieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java
src/test/java/softeer2nd/chess/sixPieces/PawnTest.java

- Pawn 클래스에 매개 변수 없는 생성자 추가
- Pawn 클래스에 white, black 상수 추가
- 패키지 명 수정 (sixPieces -> pieces)
- Board 테스트 코드 작성
- Board 검증 메서드 분리
- Pawn 생성 및 board에 추가 하는 메서드 분리
- Board의 필드에 List를 선언하지 않고 class 레벨에서 extends ArrayList<Pawn>으로 선언했는데, 이때 발생하는 문제가 있을지...
- Pawn을 생성하고 Board에 추가하는 메서드 1개를 만들었는데, Pawn 생성 메서드와 Board 추가 메서드로 또 분리하는게 맞을지...

[Hypersand] step-2 체스판 생성

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java

2차원 배열을 사용한 체스판 구성
체스판 초기화(only 폰)
체스판 출력
main() 시작, 종료 작성
체스판을 어떤 자료구조를 사용하여 구성할 지 고민이 되었다. 처음엔 ArrayList를 사용하였다가 2차원 Array를 사용하여 만들었다.

[ajsthfldu] step-3 체스판 초기화

---

src/main/java/chess/Board.java
src/main/java/chess/MainChess.java
src/main/java/chess/pieces/Pawn.java
src/main/java/softeer2nd/Main.java
src/test/java/chess/BoardTest.java
src/test/java/chess/pieces/PawnTest.java

체스판을 초기화하여 Pawn List를 체스판에 넣고 출력 실행
체스 게임을 실행하고 종료하는 함수 생성
체스판 생성 테스트
테스트 코드 리팩토링("pppppppp"와 같은 문자를 상수타입으로 지정해두었으므로 테스트 시에도 이 상수타입을 활용해야 겠다고 생각했다.)
체스판을 구현할 때 어떤 타입으로 지정해놔야 할지 고민해보았다. Pawn으로 생성한 후, 이후 다른 말이 클래스로 생성되면 이들을 묶는 추상클래스로 지네릭 타입을 변경해야 겠다고 생각했다.
Pawn List를 출력하는데 이 메서드가 추후에 필요한 이유에 대해 고민해보았다. 초기 생성을 할 때 어짜피 양끝에서 한칸 앞줄은 Pawn 8개가 배치되어야 하므로 이때 테스트를 할 용도로 사용할 수 있다고 생각했다.
Board를 어떻게 구현할 지 고민해보았는데, 체스판은 8x8로 고정이기 때문에 ArrayList를 8개 추가하는 것으로 결정하였다. Pawn이 들어가지 않는 부분은 빈 arraylist로, 비었다면 "........"을 출력하도록 하였다.
팀원의 조언으로 들었던 메인 함수에서 체스 게임 실행 메서드를 분리하여 따로 호출하는 것이 더욱 객체지향적이라 한 것에 동의하여 해당 방향으로 코드를 작성해보았다.

[jongwon] step-3 체스판 초기화

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java

- 잘못 추가된 commit 내역 revert를 통해 제거

[jjddhh] step-3 작업 revert

---

src/main/java/chess/Board.java
src/main/java/chess/ChessController.java
src/main/java/chess/pieces/Pawn.java
src/test/java/chess/BoardTest.java
src/test/java/chess/pieces/PawnTest.java

1. Pawn 색에 따른 출력 문자 부여
- white와 black에 따라 출력 문자를 상수로 정의하여 Pawn 생성 시에 부여
2. 체스판 초기화
- Board class에 initialize 함수를 정의하여 초기화 함수 구현
- 흰 Pawn과 검은 Pawn을 초기 위치에 추가
3. 리팩토링
- 중복 코드 제거 밑 정리
4. print()구현
- Board의 상태를 String으로 표현해주는 함수 구현
5. main() 구현
- game을 시작하고 끄는 등 제어 해주는 class 구현
- Board 객체에서 각 칸과 Pawn 객체를 어떻게 관리할지 고민해 보았다. 체스판의 경우 8*8 구조가 항상 유지되기 때문에 2차원 배열이 가장 합리적이라 생각하여 2차원 배열을 유지해보고자 한다.
- 리팩토링 과정에서 print와 getWhitePawnsResult, getBlackPawnsResult 함수의 출력 부분이 중복되어 이를 getLineResult로 묶어서 정리해 주었다.

[jjy0709] step-3 체스판 초기화

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Main.java
src/main/java/softeer2nd/chess/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/PawnTest.java

- 체스판 초기화
- 단위 테스트 작성
- stream을 사용해 getPawnResult 값 반환
- 기존 pieces 배열 삭제 -> board 2차원 배열로 변경
- Board의 add, size, findPawn 삭제
- 기존 작성했던 코드랑 미션의 새 요구 사항이 의도했던 방향이랑 달라 많은 수정이 있었다.
- 요구 사항을 잘 이해하고 구현한건가.. 하는 걱정도 든다.

[dohyeon-han] step-3 체스판 초기화

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Chess.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java

- 8 * 8 체스판 초기화 및 결과 출력
- 게임 시작 및 종료
- 실패 케이스를 어느정도까지 커버해야 되는지 고민
- method를 static으로 구현시 장단점
- 요구사항 추가에 따라 기존 코드 변경이 상당히 발생. 더욱 유연한 코드 작성을 고려하자
- 체스판 구현시 2차원 배열 대신, List<String> 를 사용하여 구현하였다.

[jjddhh] step-3 체스판 초기화

---

src/main/java/pieces/Pawn.java
src/main/java/softeer2nd/Board.java
src/main/java/softeer2nd/Main.java
src/test/java/pieces/PawnTest.java
src/test/java/softeer2nd/BoardTest.java

- 8*8 크기의 체스판을 ArrayList로 관리
- 체스판의 검은색 Pawn은 "P"로, 하얀색 Pawn은 "p"로 출력되며, 초기 체스판은 아래와 같은 모양
........
PPPPPPPP
........
........
........
........
pppppppp
........
- 체스 게임을 시작 하고 종료하는 main메소드를 가진 클래스 선언
- 체스판을 일반 배열로 관리하면 편할 것 같은데 ArrayList로 관리해야 하여 이에 대해 어떤식으로 구현할지 고민함
- 체스판의 상태를 문자열로 이루어진 ArrayList를 만들 때 색깔별로 구분하면 문자열에 "p", "P"를 그냥 넣으면 앞서 만든 Pawn을 사용 안하는 것 같아 이에 대해 복잡하더라도 Pawn클래스를 사용할지 말지 고민함
- 중복되는 코드가 많아 어떤식으로 리팩토링 할지 고민함

[sue06004] step-3 체스판 초기화

---

src/main/java/softeer2nd/ChessGame.java
src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java

- Pawn 색깔에 따른 출력 문자 부여 구현
- 체스판을 초기화하는 initialize 메서드 구현
- 체스 게임 시작 및 종료 간단하게 구현
- initialize 및 print 등에 대한 테스트 코드 작성
- 어떻게 하면 구현한 기능들에 대한 테스트 코드를 깔끔하게 작성할 수 있을지 많은 고민이 필요한 것 같다..
- 중복되는 메서드에 대해 분리하는 능력이 많이 부족했던 것 같다.

[Hypersand] step-3 체스판 초기화

---

src/main/java/softeer2nd/Player.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java

- 체스판 초기화
- 초기화 메소드
- 출력 메소드
- Pawn 색에 따른 출력 문자 구분
- Board 클래스 중복 리팩토링
- main 구현
- 사용자 입력 값 받기
Board의 타입을 선택하는 것이 어려웠다.
Pawn을 포함한 Bishop, Queen 등 기물들의 상위 클래스를 만들어야 하나 고민했다.
현재 Object로 설정하여 구현 중이지만, 추후 다른 기물들이 추가되면 요구사항에 맞춰 수정할 것이다.
테스트 코드 `assertEquals`, `assertThat` 이외의 다른 메소드 찾아보기

[kimahhh] step-3 체스판 초기화

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Color.java
src/main/java/softeer2nd/chess/pieces/Bishop.java
src/main/java/softeer2nd/chess/pieces/King.java
src/main/java/softeer2nd/chess/pieces/Knight.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/chess/pieces/PieceType.java
src/main/java/softeer2nd/chess/pieces/Queen.java
src/main/java/softeer2nd/chess/pieces/Rook.java
src/main/java/softeer2nd/chess/utils/StringUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java
src/test/java/softeer2nd/chess/utils/StringUtilsTest.java

- 개행 문자를 지원하는 Util 함수를 작성하였다.
- Piece 객체로 체스 말 일반화 및 각 체스말 구현, 생성 메소드를 추가하였다.
- 체스 보드판을 일관적으로 관리하고 구현하기 위해 팩토리 메소드 부분과 배치 부분을 구현하는 방법에 대해 고민이 많았다. 간단히 해당 체스판에서 체스말들의 정보를 담은 배열을 사용하여 간단히 매칭하여 구현하는 방식으로 변경하여 좀 더 수월하게 초기화 작업을 할 수 있도록 개선하였다.

[ijehyunpark] step-4 기물 배치

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Color.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/utils/StringUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java

팩토리 메서드 패턴으로 모든 기물에 대한 생성 메서드를 구현했습니다. 
isWhtie(), isBlack()
팩토리 메스드 패턴으로 구현을 했을때, 하나의 메서드에 조건문으로 구현을 할까 고민 했지만, 가독성을 위해서 각각 구현을 하는게 나을 것 같다고 생각했습니다.

[dydwo0740] step-4 기물배치

---

.idea/compiler.xml
.idea/misc.xml
build.gradle
src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/object/Pawn.java
src/test/java/softeer2nd/chess/object/PawnTest.java

- 폰 생성
- 테스트 추가
- 폴더 구조를 어떻게해야 나중에 대공사를 하지 않을까??

[LBC11] step-1 폰 생성

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Color.java
src/main/java/softeer2nd/chess/MainControl.java
src/main/java/softeer2nd/chess/MainMenu.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/main/java/softeer2nd/chess/utils/StringUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/utils/StringUtilsTest.java

- 체스판의 자료구조를 List에서 Map으로 수정
- 체스판 출력
- 체스판의 크기를 설정해 초기화하기
- 체스판 위치를 통해 폰을 찾기
- 메인메뉴로 사용자 입력에 따라 동작
- 테스트 코드
- 체스판 초기화 후 출력 시 초기화한 체스판 크기에 맞게 폰이 알맞은 위치에 배치되어 출력되어야 한다
- 폰을 체스판 특정 위치에 추가하면 체스판에 정상적으로 추가되고 추가된 폰은 일치해야 한다
- 체스판을 어떤 자료구조로 구현하는 게 좋은지
- Pawn의 representation을 어디에 저장하는 게 좋을 지
- 테스트 코드를 추가해 입력에 대한 예외 처리가 필요할 것 같다.

[Socra167] step-3 체스판 초기화

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Color.java
src/main/java/softeer2nd/chess/pieces/Bishop.java
src/main/java/softeer2nd/chess/pieces/King.java
src/main/java/softeer2nd/chess/pieces/Knight.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/chess/pieces/PieceType.java
src/main/java/softeer2nd/chess/pieces/Queen.java
src/main/java/softeer2nd/chess/pieces/Rook.java
src/main/java/softeer2nd/chess/utils/StringUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java

- 체스말 별 enum 클래스 구현하였다.
- 각 체스말 별 싱글톤 인스턴스 구현 및 팩토리 메소드 개선하였다.
- 색깔별 체스말 계수 계산 메소드 구현하였다.
- 점수 계산 메소드 구현하였다.
- 정렬 메소드 구현하였다.
- 각 체스말은 상태를 가지지 않으므로 팩토리 메소드에서 새로운 인스턴스를 생성할 필요가 없다. 따라서 각 클래스는 싱글톤으로 구현하여 하나의 인스턴스만 보유하도록 개선하였다.
- 정렬하는 요구사항이 애매해서 해결 방법에 대해 고민하였다. Map을 사용하여 각 체스말 별 점수를 계산하여 이를 Collection의 sort를 활용하여 게산하였다.

[ijehyunpark] step-5 기물 위치 부여 및 점수계산

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java

기물 색상과 종류를 상수에서 enum으로 수정
보드 자료구조를 2차원 배열에서 ArrayList<Rank>로 변경
기물 위치 반환메소드 작성
기물 추가 메소드 작성
보드 점수 계산 구현
정렬된 기물 리스트를 반환하는 메소드 작성
Piece의 객체 생성 메소드를 별도의 팩토리로 분리할 지에 대해 고민이 된다.
Piece를 인터페이스로 가지는 구체적인 기물을 만들지 고민이 된다.
기물 정렬 시 기물을 List에 저장하고 sort메소드를 사용하였는데 기물 추가와 삭제를 고려하면 해쉬맵으로 구현하는 것이 나을 것 같다.

[ajsthfldu] step-5 기물 위치 부여 및 점수계산

---

.gitignore
src/main/java/chess/Board.java
src/main/java/chess/ChessGame.java
src/main/java/chess/pieces/Piece.java
src/main/java/utils/StringUtils.java
src/test/java/chess/BoardTest.java
src/test/java/chess/pieces/PieceTest.java
src/test/java/utils/StringUtilsTest.java

- 운영체제가 지원하는 개행 문자를 제공하는 유틸리티 메소드 추가
- Pawn을 Piece로 이름 변경
- Knight, Rook, Bishop, Queen, King 기물 구현
- Piece 객체를 생성하는 팩토리 메소드 구현
- 흰색 말과 검은색 말을 구분하는 메소드 구현
- Piece의 name과 color에 의해 representation이 결정되는데, representation을 생성자의 인자로 전달받는 방식이 적절하지 않다고 생각했습니다.
- Piece와 관련된 상수를 enum으로 관리하는 것이 좋다고 생각했습니다.

[csct3434] step-4 기물 배치

---

src/main/java/chess/Board.java
src/main/java/chess/pieces/Piece.java
src/test/java/chess/BoardTest.java
src/test/java/chess/pieces/PieceTest.java

- 구현
- 리팩터링
어느 객체(Board, Piece, 혹은 별도)가 좌표 값을 가지고 있어야 하는지 계속 고민되었다. 
Piece 객체가 스스로 좌표값을 가지고 있으면 나중에 이동할 때 수정해줘야 하기도 하고, 기존에 코드가 pieceList라는 List에 Piece들을 넣어 index를 기준으로 관리하고 있어 굳이 추가적인 클래스 변수를 이용한다는 생각이 들어 꺼려진다.
Board 객체에서 Map 객체로 핸들링하는 것도 고려해 보았으나, 별도 관리가 필요하여 효율적이라 생각되진 않았다.
결국 특정 메서드에서 처리할 때 이득을 보기 위해 어느 객체 안에 정보를 포함시킬까 싶었던 것인데, 그러기 위해선 기존 구조에 전체적으로 로직 수정이 필요하여 과연 올바른 일인가 고민되었다.(결국, 현재는 어떠한 객체에도 좌표 값을 저장하고 있지 않다. 전부 Piece들이 들어간 List(Board 객체의 pieceList)의 index를 기준으로 처리한다.)
현재 정렬 관련 코드들이 과도하게 복잡하다. pawn이 같은 세로줄에 있으면 점수가 줄어드는 조건 때문인데, 더 효율적으로 구성할 방법을 생각해봐야 할 듯 하다.

[jst0951] step-5 기물 위치 부여 및 점수계산

---

src/main/java/softeer2nd/ChessGame.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Rank.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java

- 기물의 색과 종류에 따른 enum 클래스 구현
- 체스판의 모든 칸을 Piece로 초기화
- 일급 컬렉션을 이용한 Rank 클래스 구현
- 특정 위치의 기물 조회 가능하도록 구현
- 현재 체스판의 점수 계산 기능 구현
- 현재 체스판에 있는 기물의 점수를 흰 색, 검정색 각각 점수가 높은 순으로 정렬
- 일급 컬렉션을 사용했지만 제대로 사용한 건지 모르겠고, 아직 이 것이 왜 필요한지, 어떤 이점이 있는지 잘 모르겠다.
- Board 클래스의 코드가 너무 지저분한 것 같다.. 어떻게 하면 최적화 시킬 수 있을까??
- 인터페이스를 어떤 부분에 적용할 수 있는지 모르겠다..

[Hypersand] step-5 기물 위치 부여 및 점수계산

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Rank.java
src/main/java/softeer2nd/chess/exception/InvalidPositionException.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/chess/utils/PositionUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/RankTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java

보드판 초기화
기물 배치
점수 확인
기물 정렬
rank, board 클래스의 역할이 점점 너무 거대해지는 중 어떻게 효과적으로 클래스를 나눌 수 있을것인지.
중복을 줄이자니 인자 의존도가 너무 올라가고 인자를 줄이자니 중복이 늘어난다 무엇이 좋은 방법일까?
Rank를 통해 보드의 행을 구현하니 점수 계산을 할 때 로직이 별로인 것 같음. 자료구조나 로직 더 생각해볼 필요 있음.
인터페이스 쓰려면 기물별로 클래스를 생성해야 할 것 같은데 맞는지 모르겠다.

[RecordOfJun] step-5 기물 위치 부여 및 점수계산

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Chess.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/ChessTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java

- Pawn class
+ representation field 추가
+ field에 대한 접근 제어자 private로 수정
- Board class
+ map을 사용해 보드판 구현
+ ArrayList를 사용해 현재 보드판에 있는 기물들을 저장 
+ print() 구현
- Chess class
+ start() 구현
+ end() 구현
- Main class 구현
1. 학습 목표중 하나인 2차원 배열의 대안을 생각해보자
- 알고리즘을 공부하면서 n차원 배열을 더 낮은 차원으로 이끌어 내야 하는 상황이 많이 있었다. 
- 그 당시 hash등의 방법을 사용했는데 이와 비슷하게 접근해보았다.
- 먼저 idx의 범위가 0~7이므로 row * 10 + col을 idx로 사용하는 1차원 배열을 떠올렸다.
- 그런데 중간중간 낭비되는 메모리 공간이 생기게 된다. 이 때문에 map을 사용해서 해결하였다.
2. 중복 제거에 대한 그동안의 오해
- 사실 미션에서 상수를 선언하여 중복을 제거하라고 했을 때 긴가민가 했었다.
- 해당 부분의 코드양이 줄거나 변화가 없었기 때문에 굳이?? 라고 생각했다.
- 하지만 고민하다보니 상수를 사용하는 것은 해당 변수를 선언하고, 사용되고, gc에 의해 제거되는 일련의 활동이 반복되고 있다는 것을 꺠달았다.
- 앞으로 리팩토링을 할 때 눈에 보이는 코드의 중복만을 제거하는 것이 아니라 코드가 실제로 구동될 때 발생하는 중복도 제거하기 위해 고민해야 겠다.
3. 현재 사용하지 않는 함수들은 어떻게 해야 하는가?
- 현재의 미션 단계에서 Board class의 add()등의 함수들은 사용되지 …

[LBC11] step-3 체스판 초기화

---

.idea/compiler.xml
.idea/misc.xml
src/main/java/chess/Board.java
src/main/java/chess/Position.java
src/main/java/chess/pieces/Piece.java
src/main/java/chess/pieces/Rank.java
src/test/java/chess/BoardTest.java
src/test/java/chess/pieces/PieceTest.java

- Piece 관련 상수에 enum을 적용
- 체스판의 모든 칸을 Piece로 초기화하는 기능
- 기물과 색에 해당하는 기물의 개수를 반환하는 기능
- 주어진 위치의 기물을 조회하는 기능
- 임의의 기물을 체스판 위에 추가하는 기능
- 점수 계산 기능
- 점수로 기물들을 정렬하는 기능
- 기물이나 랭크 조회 시, rankIndex와 fileIndex를 직접 사용하는 방식이 적절하지 않아 개선이 필요해 보임

[csct3434] step-5 기물 위치 부여 및 점수계산

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Chess.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/utils/StringUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java
src/test/java/softeer2nd/utils/StringUtilsTest.java

- Piece class
+ Pawn class 에서 Piece로 이름 변경
+ value object 패턴 사용
+ 팩토리 메소드 패턴 사용
+ isBlack(), isWhite() 구현
- Board class
+ Piece의 수정에 따른 변경
+ Pawn을 제외한 기물 배치 구현
- StringUtils
+ Uppercase 추가
- Chess
+ board가 프린트 되지 않는 에러 수정
- Piece 안의 Color, Type enum을 밖으로 빼야 하는가?
+ Board class에서도 위의 enum을 사용하기에 Piece안의 정보를 가져와서 사용한다는 점에서 결합도가 증가하지 않을까 고민
+ Piece class가 애초에 value object로 data를 제공해주는 객체이기에 지금의 상태로도 괜찮다는 결론을 내렸다.
- Factory method가 지금으로도 충분한가?
+ 관련 블로그를 읽으면서 추상 클래스를 이용하는 방법, 인터페이스를 이용하는 방법이 있었다.
+ 이 중 어떠한 방식이 좋을까 더 고민해보자.

[이병찬] step-4 기물 배치

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/MainControl.java
src/main/java/softeer2nd/chess/game/GameManager.java
src/main/java/softeer2nd/chess/game/GameMenu.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/chess/utils/StringUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/HelloTest.java
src/test/java/softeer2nd/chess/game/GameManagerTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java
src/test/java/softeer2nd/chess/utils/StringUtilsTest.java

- Piece Color, Type을 상수 구현에서 enum으로 변경
- Blank piece로 체스판 초기화
- 체스판 자료구조를 Map에서 List로 변경
- 문자열 위치 지정으로 기물 조회하기
- Collection 동작들을 stream 으로 리팩토링
- 기물을 체스판 임의 위치에 추가하기
- 체스판의 기물 색별 점수 계산
- 기존 for문으로 구현된 showBoard()를 Stream으로 변경했는데 특정 문자 수마다 개행을 삽입하는 동작을 어떻게 구현할 지 고민이었다. Stream만으로 해결하고 싶었지만 간단하게는 해결되지 않아서 Stream으로 representation으로 변환 후 for loop로 개행을 삽입했다.
- 폰이 세로 위치로 놓였을 때 점수를 어떻게 계산할지 고민했다. 일단 체스판의 점수를 합산한 후, 세로로 놓인 폰의 수를 찾는 메소드로 폰 점수의 절반을 차감하도록 구현했다.
- enum 데이터에 대한 getter 메소드의 접근 지정자를 어떻게 지정해야 할지 고민했다. 여러 데이터를 처리하는 로직은 데이터 밖에 있어서 getter를 사용할 수 밖에 없었는데, 최대한 private를 사용하도록 노력했다. enum에 private getter를 두고 enum의 getter를 사용하는 public getter를 Piece에 만들어 구현했다.
- 스트림을 사용하니 for문을 사용할 때 보다 코드가 훨씬 간결하고 가독성이 좋아진 것 같다.
- TDD 방식도 확실히 객체지향에 도움이 되고 있는 게 느껴진다.
- 테스트 코드가 짧거나 테스트 내용이 간단할 때 BDD의 given / when / …

[신동우] step-5 기물 위치 부여 및 점수계산

---

src/main/java/chess/Board.java
src/main/java/chess/Position.java
src/main/java/chess/Rank.java
src/main/java/chess/pieces/Piece.java
src/test/java/chess/BoardTest.java
src/test/java/chess/pieces/PieceTest.java

- 기물의 색/종류 Enum 구현 및 적용
- 팩토리 메소드 리팩토링
- 빈 칸을 Piece로 변경
- 기물과 색에 해당하는 개수 반환
- 주어진 위치의 기물 반환
- 기물 추가 구현
- 점수 계산 및 점수에 따라 기물 정렬
- 리팩토링 할 부분
- Enum의 사용과 적용에 따른 부분
- 점수 계산 방법

[정지영] step-5 기물 위치 부여 및 점수계산

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Chess.java
src/main/java/softeer2nd/chess/Constants.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java

- Piece
+ 기존의 enum(Color, Type) constants class로 추출
+ 빈 칸 피스 type 이름, 색 이름 변경
- Board
+ emptyInitialize() 구현
+ 기물과 색에 따른 기물들의 개수 반환 기능 구현
+ "a8" 과 같은 position을 받아 해당 위치의 기물 반환 기능 구현
+ 임의의 기물을 체스판 위에 추가하는 기능 추가
+ 기물의 점수가 높은 순으로 정렬 기능 추가
- 추가된 클래스/enum
+ Constant class 추가
+ SortOrder enum 추가
- 객체지향의 원칙을 어디까지 지켜야 할까???
+ 캡슐화를 엄격하게 지키자면 piece 의 속성인 type, color에 다른 class가 접근하여 직접 사용하면 안 된다.
+ 미션지의 isBlack(), createWhitePawn() 등의 메소드는 위의 원칙을 고려한 매소드로 보인다.
+ 그래서 type 역시 board class에서 접근하는 것을 방지하기 위해 isPawn()등의 메소드를 추가하였었다.
+ 하지만 위의 방식을 고수하다보니 중복이 하염없이 증가하는 문제가 발생했다. type은 6가지이고 color는 2가지이다. 그래서 createPiece만 12개가, isPawn() 과 같이 확인을 하는 메소드가 8개가 생겼다.
+ 여기서 representation, point를 가져오는 method를 추가하려다 무언가 잘못되었다는 생각이 강하게 들었다.
+ color, type enum을 piece 밖으로 빼내기만 하면 위의 무수히 중복되는 메소드들은 매우 간결해진다.
+ 리팩토링의 기준 …

[이병찬] step-5 기물 위치 부여 및 점수계산

---

src/main/java/pieces/Bishop.java
src/main/java/pieces/Blank.java
src/main/java/pieces/King.java
src/main/java/pieces/Knight.java
src/main/java/pieces/Pawn.java
src/main/java/pieces/Piece.java
src/main/java/pieces/Queen.java
src/main/java/pieces/Rook.java
src/main/java/softeer2nd/Board.java
src/main/java/softeer2nd/ChessGame.java
src/main/java/softeer2nd/ChessView.java
src/main/java/softeer2nd/Main.java
src/main/java/utils/Direction.java
src/main/java/utils/Position.java
src/main/java/utils/Rank.java
src/test/java/pieces/BishopTest.java
src/test/java/pieces/KingTest.java
src/test/java/pieces/KnightTest.java
src/test/java/pieces/PawnTest.java
src/test/java/pieces/PieceTest.java
src/test/java/pieces/QueenTest.java
src/test/java/pieces/RookTest.java
src/test/java/softeer2nd/BoardTest.java
src/test/java/softeer2nd/ChessGameTest.java
src/test/java/softeer2nd/ChessViewTest.java

- String으로 두개의 위치(sourcePos, targetPos)를 받고, 이 두 값을  Position객체로 변환 한 후 sourcePos에 위치한  피스를 targetPos로 이동시킴
- Board클래스의 역할을 ChessGame과 ChessView클래스로 분담시킴
- Piece클래스를 상속받는 King, Queen, Knight 등의 모든 타입의 자식클래스 생성
- 각 자식 클래스별로 verifyMovePosition을 구현
- 각 기물들의 Test 클래스를 따로 생성
- Piece클래스에 추상 메소드로 verifyMovePosition을 추가하고 각 기물 클래스에서 이를 구현해보니 Pawn을 제외한 모든 클래스가 똑같은 코드로 구현되었다. 그래서 일단 해당 코드를 Piece클래스의 메소드로 넣어서 중복을 제거하였다. 하지만 이러면 추상메소드를 추가한 이유가 없는 것 같다.

[김우혁] step-6 기물 이동 구현

---

src/main/java/Main.java
src/main/java/chess/Board.java
src/main/java/chess/Game.java
src/main/java/chess/Position.java
src/main/java/chess/View.java
src/main/java/chess/pieces/Bishop.java
src/main/java/chess/pieces/Blank.java
src/main/java/chess/pieces/King.java
src/main/java/chess/pieces/Knight.java
src/main/java/chess/pieces/Pawn.java
src/main/java/chess/pieces/Piece.java
src/main/java/chess/pieces/Queen.java
src/main/java/chess/pieces/Rook.java
src/test/java/MainTest.java
src/test/java/chess/BoardTest.java
src/test/java/chess/GameTest.java
src/test/java/chess/PositionTest.java
src/test/java/chess/ViewTest.java
src/test/java/chess/pieces/BishopTest.java
src/test/java/chess/pieces/BlankTest.java
src/test/java/chess/pieces/KingTest.java
src/test/java/chess/pieces/KnightTest.java
src/test/java/chess/pieces/PawnTest.java
src/test/java/chess/pieces/QueenTest.java
src/test/java/chess/pieces/RookTest.java

(2023.07.11 회고 중)
protected를 이용하면 상속 관계에 있는 class끼리 변수/메서드를 공유할 수 있다.(외부에는 은닉된 상태를 유지하며!)
이를 이용해서 부모 객체인 Piece가 자식 객체의 protected 생성자를 불러오게 하여, 팩토리 메서드를 전부 각 기물의 클래스에서 구현하는 것을 회피하였다.(부모에도 createWhitePawn, 자식에도 createWhitePawn 메소드가 존재하는 것을 회피) 
그런데 팀원분에게 이런 패턴이 좋은 패턴인지 여쭤보니 보통 부모 객체는 자식 객체에 의존하면 안 되므로 좋은 패턴은 아닌 듯 하다고 하셔서 고민이 조금 된다. 사실 생성자정도는 괜찮을 것  같기도 한데, Piece 객체 내에선 이제 자식 객체의 생성자를 마음대로 가져다 쓸 수 있어 잘못된 팩토리 메서드가 생길 수도 있긴 하다. 
1. 기존에 rebase/merge 없이 진행하다 보니 매번 기존 커밋을 전부 올렸는데, rebase 후 깔끔하게 기존에서 수정된 부분만 올라간다.
2. 움직임까지 구현이 완료된 것이긴 하지만, 기본 행마법에 대해서만 완료되었고 캐슬링이나 폰의 특수 이동 등에 대해서는 진행되지 않았다. 체스의 세부 규칙보단 구조화가 중요하다 생각하여 해당 부분까지만 진행하였다. 현재 구조에선 verifyMovePosition()만을 수정하면 되는 문제여서 크게 어렵진 않을 듯 하다.

[정성태] step-6 기물 이동 구현

---

src/main/java/chess/MainChess.java
src/main/java/chess/controller/ChessGame.java
src/main/java/chess/exception/ExceptionMessageHandler.java
src/main/java/chess/exception/InvalidMoveException.java
src/main/java/chess/exception/InvalidPositionException.java
src/main/java/chess/exception/PieceNotExistException.java
src/main/java/chess/model/Position.java
src/main/java/chess/model/board/Board.java
src/main/java/chess/model/pieces/Bishop.java
src/main/java/chess/model/pieces/BlankPiece.java
src/main/java/chess/model/pieces/King.java
src/main/java/chess/model/pieces/Knight.java
src/main/java/chess/model/pieces/NoPiece.java
src/main/java/chess/model/pieces/Pawn.java
src/main/java/chess/model/pieces/Piece.java
src/main/java/chess/model/pieces/PieceColor.java
src/main/java/chess/model/pieces/PieceCreator.java
src/main/java/chess/model/pieces/PieceMoveMore.java
src/main/java/chess/model/pieces/Queen.java
src/main/java/chess/model/pieces/Rook.java

- 예외처리를 각 상황에 맞는 ExceptionHandler를 새로 생성하여 이를 참조하도록 함.
- 기타 깔끔하지 않게 작성된 코드(피드백받은) 리팩토링
- 기물 이동 시 이동이 불가한 위치임에도 이동을 시도하여 프로그램이 종료되는 버그 수정
- 각 차례에 자신의 기물만을 이동할 수 있도록 상태 생성
- validation 부분의 불필요한 if문 제거
- 기물의 공통 메서드를 추상 클래스에 작성하여 코드 중복 제거
step6에 이어 MVC패턴을 최대한 지키면서 해보고 싶어 각 클래스의 역할에 대한 고민을 많이 하였다. 피어 세션과 별도로 다른 분들과 이야기를 나누어보면 서로 세부적으로 로직을 분리하는 방법이 달랐는데, 또 그렇게 한 이유를 들어보면 모두가 납득이 갈만한 이유였다. 정답이라고 할만한 형식은 어떻게 될지 궁금했다.
생성자에 방향을 넣으면 추상클래스가 필요가 없어지는데, 코드를 수정하기 망설여졌었다. 막상 보니 이미 Color에 대해서는 생성자로 주입하고 있었는데, 그렇다면 왜 방향을 넣는 것에는 망설여졌는지 생각해보았다. 일단은 Pawn에서 색상에 따라 방향이 다르기 때문에 분리하였지만, 생성자 주입과 메서드에서 참조하는 방법 중 어떤 방법이 더 나을지 고민해보아야 할 것 같다.
체스의 웹구현까지 진행하려 했고, 이미 보드판까지는 만들었지만, 기타 백에서 구현해야하는 디테일한 체스 세부기능들을 구현하는데 시간을 투자하면 오히려 짧은 부트캠프 시간을 아깝게 보내게 될 수도 있다고 생각하여 WAS 이후 시간이 남게 된다면 웹으로 구현하기로 하였다.

[김종원] step-7 예외 처리

---

README.md
src/main/java/softeer2nd/Player.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Board/Board.java
src/main/java/softeer2nd/chess/Board/ChessGame.java
src/main/java/softeer2nd/chess/Board/ChessView.java
src/main/java/softeer2nd/chess/Board/Rank.java
src/main/java/softeer2nd/chess/Direction.java
src/main/java/softeer2nd/chess/Position.java
src/main/java/softeer2nd/chess/pieces/Bishop.java
src/main/java/softeer2nd/chess/pieces/Blank.java
src/main/java/softeer2nd/chess/pieces/King.java
src/main/java/softeer2nd/chess/pieces/Knight.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/chess/pieces/Queen.java
src/main/java/softeer2nd/chess/pieces/Rook.java
src/main/java/softeer2nd/exception/Exception.java
src/main/java/softeer2nd/utils/StringUtils.java
src/test/java/softeer2nd/chess/Board/BoardTest.java
src/test/java/softeer2nd/chess/Board/ChessGameTest.java
src/test/java/softeer2nd/chess/Board/ChessViewTest.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/PositionTest.java
src/test/java/softeer2nd/chess/pieces/BishopTest.java
src/test/java/softeer2nd/chess/pieces/KingTest.java
src/test/java/softeer2nd/chess/pieces/KnightTest.java
src/test/java/softeer2nd/chess/pieces/PawnTest.java
src/test/java/softeer2nd/chess/pieces/QueenTest.java
src/test/java/softeer2nd/chess/pieces/RookTest.java

- 무분별한 createBlank()로 인한 객체 생성을 막기 위해
- 이동할 때 targetPosition에 말이 없다면 -> targetPosition에 있던 Blank를 sourcePosition으로 이동
- 이동할 때 targetPosition에 말이 있다면 -> sourcePosition에 새로운 Blank 생성
- Piece가 Position 정보를 갖고 있게 할지
- 게임을 진행할 때 Piece가 Position 정보를 가지고 하는 일이 없기 때문에 안 가지고 있어도 되겠다고 생각
- Board가 Piece 정보를 가지고 있게 함
- static을 남용하는 것은 아닌지
- static 변수는 클래스가 로딩될 때 한 번 생성되고, JVM이 종료될 때까지 메모리에 남아있음 -> 메모리 누수 가능성
- 캡슐화하지 않음 -> 객체지향적이지 않음
- 여러 스레드가 동시에 static 메서드를 호출하거나 static 변수를 변경한다면 동기화 문제 발생
- 자주 사용되는 메서드와 변수만 static으로 두기로 결정
- Board의 책임을 나눠가진 클래스(ChessGame, ChessView)가 Board를 매개변수로 가지고 있는데, 클래스의 책임을 나누는 의미가 있는지
- Exception을 한 군데 모아서 사용하는 것이 맞는지
- 규모가 작은 프로젝트는 상관 없지만, 규모가 큰 프로젝트라면 exception도 책임에 따라 다른 enum 클래스로 나누어서 작성하는 것이 낫다고 생각

[김아현] step-6 기물 이동 구현

---

src/main/java/Main.java
src/main/java/chess/Board.java
src/main/java/chess/Game.java
src/main/java/chess/Position.java
src/main/java/chess/pieces/Bishop.java
src/main/java/chess/pieces/Piece.java
src/test/java/chess/BoardTest.java
src/test/java/chess/GameTest.java
src/test/java/chess/PositionTest.java
src/test/java/chess/ViewTest.java

1. pieceList를 일급 컬렉션으로 별도로 구성해야 하는지 끝까지 고민됐었다. 일급 컬렉션으로 따로 빼면 더욱 pieceList를 안전하게 사용할 수 있겠지만, 비즈니스로직(게임 관련 로직)은 전부 Game 클래스에 위임되어 있어 현재 Board안에서 처리하는 로직이 일급 컬렉션 내부에서 처리하면 되는 로직이라.. Board가 단순한 껍데기가 될 수 있겠다 싶었다. 그래서 결국 직접 수정은 막도록 구성하고, 별도로 메서드를 빼 일급 컬렉션은 아니지만 비슷하게 구성했다. 지금 생각하기엔 괜찮은 설계인듯 하다.
2. 현재 exception은 전부 IllegalArgumentException으로 정의되어 있다. 다른 팀원들을 보니 많이들 별도로 각 오류에 대한 클래스를 생성해서 진행하신 것 같은데, 사실 exception 처리에 별다른 로직 처리가 필요하다고 보여지진 않아 올바른 설계인지 고민되었다. 그러던 와중 https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/ 글을 보게 되어 사전 정의된 exception을 쓰는 것도 괜찮겠다 싶어 위처럼 진행하였다. 추후에 exception이 좀 복잡하게 나뉘어지게 되면 custom exception도 시도해보려 한다.
1. Exception 관련해서 시행착오가 많았다. Exception 처리라곤 기존에 그냥 throws Exception 이런식으로 대충 구성했었는데, 제대로 어떻게 동작하는지 이해하게 되어 수확이 있었다.
2. 드디어 step7이 끝났다. 세부 로직을 다 만들진 못해 좀 아쉽지만, …

[정성태] step-7 예외 처리

---

src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Position.java
src/main/java/softeer2nd/chess/Rank.java
src/main/java/softeer2nd/chess/exception/BlankPieceException.java
src/main/java/softeer2nd/chess/exception/InvalidMovementException.java
src/main/java/softeer2nd/chess/exception/InvalidPositionException.java
src/main/java/softeer2nd/chess/exception/InvalidSameColorException.java
src/main/java/softeer2nd/chess/exception/InvalidTurnException.java
src/main/java/softeer2nd/chess/game/ChessGame.java
src/main/java/softeer2nd/chess/game/Turn.java
src/main/java/softeer2nd/chess/pieces/Blank.java
src/main/java/softeer2nd/chess/pieces/King.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/chess/simulator/ChessSimulator.java
src/main/java/softeer2nd/chess/view/ChessView.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/game/ChessGameTest.java
src/test/java/softeer2nd/chess/game/TurnTest.java
src/test/java/softeer2nd/chess/pieces/BishopTest.java
src/test/java/softeer2nd/chess/pieces/KingTest.java
src/test/java/softeer2nd/chess/pieces/KnightTest.java
src/test/java/softeer2nd/chess/pieces/QueenTest.java
src/test/java/softeer2nd/chess/pieces/RookTest.java

- step6에서 이미 모든 예외 처리를 완료했기 때문에 리팩토링에 신경 썼다.
- 불필요한 메서드 제거
- 의미가 모호한 메서드명 변경
- 예외 처리의 메세지는 Exception Class에서 관리하도록 수정
- 매직 넘버 제거
- ChessGame 클래스의 move 메서드의 코드 길이가 너무 길다.
분명, 하는 일이 많아서 그런거 같긴 한데, 어떤 식으로 분리해야 할 지 잘 모르겠다.

[손승완] step-7 예외 처리

---

src/main/java/softeer2nd/Main.java
src/main/java/softeer2nd/chess/Board.java
src/main/java/softeer2nd/chess/Direction.java
src/main/java/softeer2nd/chess/Game.java
src/main/java/softeer2nd/chess/Observer.java
src/main/java/softeer2nd/chess/Position.java
src/main/java/softeer2nd/chess/Rank.java
src/main/java/softeer2nd/chess/TerminalView.java
src/main/java/softeer2nd/chess/exceptions/InvalidMoveException.java
src/main/java/softeer2nd/chess/exceptions/InvalidPositionException.java
src/main/java/softeer2nd/chess/exceptions/InvalidTurnException.java
src/main/java/softeer2nd/chess/pieces/Bishop.java
src/main/java/softeer2nd/chess/pieces/Blank.java
src/main/java/softeer2nd/chess/pieces/King.java
src/main/java/softeer2nd/chess/pieces/Knight.java
src/main/java/softeer2nd/chess/pieces/Pawn.java
src/main/java/softeer2nd/chess/pieces/Piece.java
src/main/java/softeer2nd/chess/pieces/Queen.java
src/main/java/softeer2nd/chess/pieces/Rook.java
src/main/java/softeer2nd/utils/StringUtils.java
src/test/java/softeer2nd/chess/BoardTest.java
src/test/java/softeer2nd/chess/GameTest.java
src/test/java/softeer2nd/chess/PositionTest.java
src/test/java/softeer2nd/chess/RankTest.java

- 체스 비정상적인 입력에 대한 예외처리
- 잘못된 위치에 대한 예외처리
- 잘못된 이동에 대한 예외처리
- 흰색과 검은색이 번갈아 가며 입력하도록 턴 구현
- 핵심 로직 수정
- 클래스의 역할에 맞춰 분리하는 것에 대해서 고민이 많았다.
- MVC패턴에서 입력을 뷰와 컨트롤러 중 어디에서 처리해야 할 지와 컨트롤러와 모델의 역할을 분리하는 것에 대해 고민이 많이 되었다.

[홍선기] step-7 예외 처리

---

src/main/java/softeer2nd/chess/Board/Board.java
src/main/java/softeer2nd/chess/Board/ChessView.java
src/main/java/softeer2nd/chess/Board/Constants.java
src/main/java/softeer2nd/chess/Board/PointCalculator.java
src/main/java/softeer2nd/chess/Board/Position.java
src/main/java/softeer2nd/chess/Board/Rank.java
src/main/java/softeer2nd/chess/Board/RankFactory.java
src/main/java/softeer2nd/chess/Chess.java
src/main/java/softeer2nd/chess/exception/commandException/InvalidCommandException.java
src/main/java/softeer2nd/chess/exception/moveException/InvalidMoveException.java
src/main/java/softeer2nd/chess/exception/pieceException/InvalidPieceFieldException.java
src/main/java/softeer2nd/chess/exception/positionException/InvalidPositionException.java
src/main/java/softeer2nd/chess/pieces/PieceFactory.java
src/main/java/softeer2nd/utils/StringUtils.java
src/test/java/softeer2nd/chess/board/BoardTest.java
src/test/java/softeer2nd/chess/board/RankFactoryTest.java
src/test/java/softeer2nd/chess/board/RankTest.java
src/test/java/softeer2nd/chess/board/chessViewTest.java
src/test/java/softeer2nd/chess/pieces/PieceFactoryTest.java
src/test/java/softeer2nd/chess/pieces/PieceTest.java

1. Chess 클래스
- 색깔을 통해 각 플레이어가 이동할 수 있는 기물 설정
- switch문을 try-catch안에 집어넣어 각 예외 발생들 처리 
2. 예외 클래스
- Move관련 예외 추가(ex. 빈 곳을 잡으려할 때, 기물의 색과 플레이어의 색이 같지 않을 때)
1. 예외 처리를 체계적으로 관리할 수 없을까??
- 예외 클래스가 나열되다 보니 뭐가 뭐를 위한 것인지 알기 어려웠다.
- 그래서 관련 예외중 대표격으로 하나를 만들고 나머지 예외가 그것을 상속받는 형식을 사용했다.
2. 예외에서 발생할 수 있는 transaction을 어떻게 해결할까?
- 코드 중간에 예외가 발생할 경우 앞의 부분은 결과가 반영되고 뒷부분은 반영이 안 되어 상태가 이상해지는 문제가 발생할 수 있다.
- 정말 다행히도 그동안 메소드를 실행시키기 전에 유효성 검사를 진행하기에 일부분만 실행이 되는 경우는 존재하지 않았다.
- 추가로, switch문을 try-catch로 감싸서 명령어를 단위로 transaction을 진행하는 방식을 사용했다.

[이병찬] step-7 예외처리.md
